### ISSUE TITLE
Suggestion: Wrap startup file IO error handler, .. etc.

### ISSUE THREAD

**Issue by DanRathbun** [thomthom/extension-sources#50]
It is safer to have file IO in a rescuable block.
You can also cut down on the number of orphaned local variables that hang around.

I've found that most devs are assigning their extension object to a local constant `EXTENSION`.
What's the point of letting the hash of meta data hang around in memory? (ie, the data is loaded into the object and later retrievable by API getter methods.)

Anyway the following has my ideas, take it or leave it:
```ruby
  unless file_loaded?(__FILE__)
    begin
      # Read Extension meta-data from disk:
      json = File.read(File.join(PATH, 'extension.json'))
    rescue => err
      puts Module::nesting[0].name << 'not loaded ...'
      puts err.inspect
    else
      EXTENSION = SketchupExtension.new(
        Module::nesting[0].name.split('::').last, # temp name
        File.join(PATH, 'bootstrap') # loader path
      )

      EXTENSION.instance_eval {
        # Process Extension meta-data:
        ::JSON.parse(json).each_pair do |key,val|
          self.method("#{key}=").call(val) if self.respond_to?(key)
        end
        # Register with the SketchUp ExtensionsManager:
        Sketchup.register_extension(self, true)
      }
    ensure
      json = nil # mark for GC
    end
  end # Run once at startup block
```

**Comment by thomthom** [comment]
> What's the point of letting the hash of meta data hang around in memory?

The members of that hash is used by the extension in various places. It's not a huge amount of memory that I worry about. I think I prefer that than reading from disk to access the members every time.

> It is safer to have file IO in a rescuable block.

What would the rescue block do? If that file is missing then the extension is corrupted somehow. Doesn't seem worth the extra logic to recover with a temporary name. A case where a hard failure is better than ignoring it IMO.

**Comment by DanRathbun** [comment]
> I think I prefer that than reading from disk to access the members every time.

As I had said. They are loaded as properties of the [`SketchupExtension`](https://ruby.sketchup.com/SketchupExtension.html) object, which can be queried at any later time, rather than reloading from disk (which is **not** in any way what I suggested.)

Those (extras) that I had skipped with the ` if self.respond_to?(key)` clause could instead be attached as singleton attributes.

> What would the rescue block do?

As shown above, it prevents the creation of a [`SketchupExtension`](https://ruby.sketchup.com/SketchupExtension.html) object with blank properties, and unlike a "hard failure" which outputs a cryptic IO exception message to the user, it has the opportunity to print a console message that explains something the user can understand and report back.
I showed that it informed the user right away **what extension** is having the error. However I did not "simplify" the exception error into something less cryptic. But this could be done.
This line ...
```ruby
      puts err.inspect
```
... could be ...
```ruby
      puts "Error reading 'extension.json' file."
```

----

Anyway. It was only some suggestions as I dislike wasting user memory with data that SketchUp is going to hold (in the [`Sketchup::ExtensionsManager`](https://ruby.sketchup.com/Sketchup/ExtensionsManager.html),) or local variables that go unused afterward and never get cleaned up.

And... generally I always suggest wrapping up any file IO to handle errors more gracefully.

**Comment by thomthom** [comment]
The absence of `extension.json` is as critial as the absense of any other `.rb` file - I don't see the point of trying to handle that. At least not by the extension itself. SketchUp on the other hand could improve on loading error handling (which is in the works btw). An error reading `extension.json` wouldn't make more sense to an end user by rephrasing it. An developer can read the stack trace just as well.

The memory usage in this case in miniscule. And the data involved is relevant for the life-time of the. The strings in the hash that is also used by `SketchupExtension` is also shared. `SketchupExtension` doesn't make a copy of the params passed in.

```rb
TT::Plugins::ExtensionSources::EXTENSION[:name].object_id
# => 380

Sketchup.extensions[TT::Plugins::ExtensionSources::EXTENSION[:name]].name.object_id
# => 380
```

The proposed changes seems to me to have very little practical benefits, while making the logic more complicated.

Thank you for your suggestion, I do appreciate that, but I'm going to keep the extension registration as-is. I got a list of other improvements that has a higher value-gain and priority: https://github.com/thomthom/extension-sources/milestones

**Comment by DanRathbun** [comment]
> SketchUp on the other hand could improve on loading error handling (which is in the works btw).

Oh? This is good to hear!
