### ISSUE TITLE
Unexpected configurations shared between different SketchUp versions

### ISSUE THREAD

**Issue by zfjoy520** [thomthom/extension-sources#55]
Different SketchUp versions use the same configurations path in ExtensionSourcesController#storage_dir:
https://github.com/thomthom/extension-sources/blob/1e71009b2acc24921e4961bbbfce52eda2579af2/src/tt_extension_sources/controller/extension_sources_controller.rb#L417-L420

This results in the same project being loaded in every Sketchup version, which is probably not what I want in my development work!
What should I do if I want to configure the project independently for each Sketchup version?

**Comment by thomthom** [comment]
Yea, currently it's shared across all. Have had some ideas about per-verssion config: https://github.com/thomthom/extension-sources/issues/25

For now I just disable the extensions in the Extension Manager.
